[package]
name = "cons"
version = "0.0.1"
authors = ["bosilan"]

[dependencies]
easy_util = {git = "https://limitee:20131988lm@github.com/limitee/easy_util.git"}
lazy_static = { git = "https://github.com/rust-lang-nursery/lazy-static.rs.git" }
rustc-serialize = "0.3.16"

