[package]
name = "elog"
version = "0.0.1"
authors = ["bosilan"]

[dependencies]
log = "0.3.5"
chrono = "0.2.20"
colored = "1.1.0"
rustc-serialize = "0.3.16"

easy_config = {version="0.0.1", path="../../../easy_config"}
